---

- yum:
    name: http://yum.postgresql.org/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
  when: ansible_distribution == 'CentOS'
    
- yum: 
    name: yum install https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-redhat10-10-2.noarch.rpm
  when: ansible_distribution == 'Red Hat Enterprise Linux'

- yum:
    name: postgresql10-server 
    state: latest

- yum: 
    name: postgresql10
    state: latest

- shell: /usr/pgsql-10/bin/postgresql-10-setup initdb 
 
- service: name=postgresql-10 state=restarted enabled=yes
